# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
#

font_family JetBrainsMono Nerd Font Propo
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 11.5
# modify_font cell_width 105%
modify_font cell_width 110%

background_opacity 0.5

# Smooth Cursor
cursor_trail 3
cursor_trail_decay 0.1 0.4

sync-to-monitor yes
repaint_delay 10

cursor_blink_interval 0.5

# Padding
# window_padding_width 5 10 5 10
