#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
exec-once = waybar
# exec-once = ~/.config/waybar/scripts/launch.sh
# exec-once = hyprpaper
exec-once = awww-daemon
exec-once = ~/.config/awww/init.sh
exec-once = waybar_autohide &
exec-once = fcitx5
exec-once = elephant
exec-once = walker --gapplication-service
# exec-once = eww open bar_widget & eww open menuctl & eww open wifictl & eww open calendar & eww open usrctl
exec-once = [workspace 1 silent] kitty
exec-once = [workspace 2 silent] kitty
exec-once = [workspace 10 silent] kitty
exec-once = [workspace special:magic silent] zen
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# SSH-Key
exec-once = ~/.config/hypr/ssh-agent.sh

# XDG-Desktop-Portal
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOPexec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user start graphical-session.target
exec-once = xwaylandvideobridge
